# Generated by Django 3.2.5 on 2025-03-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PARAMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('libelle', models.TextField()),
                ('libelle_ang', models.TextField()),
                ('responsable_collecte', models.TextField()),
                ('description', models.TextField()),
                ('description_ang', models.TextField()),
                ('composite', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=255)),
                ('formule', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('EN VEILLE', 'En Veille')], max_length=255)),
                ('calcule', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('frequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='PARAMS.frequence')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='PARAMS.niveau')),
                ('sousysteme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='PARAMS.sousysteme')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='PARAMS.unite')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('libelle', models.TextField()),
                ('libelle_ang', models.TextField()),
                ('api_url', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicateurVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateur_variables', to='INDICATEUR.indicateur')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateur_variables', to='INDICATEUR.variable')),
            ],
        ),
    ]
