# Generated by Django 3.2.5 on 2024-10-23 21:25

import DIVADMIN.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeBassin', models.CharField(max_length=255)),
                ('nomBassin', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeDivision', models.CharField(max_length=255)),
                ('nomDivision', models.TextField(blank=True)),
                ('niveauDivision', models.IntegerField(blank=True, null=True)),
                ('libelleNiveauDivision', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=DIVADMIN.models.upload_path)),
                ('divisionadministrative_id', models.PositiveIntegerField(blank=True, null=True)),
                ('id_pays', models.PositiveIntegerField(blank=True, null=True)),
                ('bassin', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeZone', models.CharField(max_length=255)),
                ('nomZone', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneDivisionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateField()),
                ('date_sortie', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonedivisionadministratives', to='DIVADMIN.divisionadministrative')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonedivisionadministratives', to='DIVADMIN.zone')),
            ],
        ),
    ]
