# Generated by Django 3.2.5 on 2025-03-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('INDICATEUR', '0001_initial'),
        ('PRODAGRIC', '0001_initial'),
        ('DIVADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitComext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=255)),
                ('nomProduit', models.TextField(blank=True)),
                ('nomProduit_ang', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarchBetailVarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('variable', models.IntegerField(blank=True, null=True)),
                ('nom_marche', models.CharField(max_length=255)),
                ('type_prix', models.CharField(max_length=255)),
                ('code_unite', models.CharField(max_length=255)),
                ('code_devise', models.CharField(max_length=255)),
                ('niveau1_id', models.IntegerField(blank=True, null=True)),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_betail_var_items', to='DIVADMIN.divisionadministrative')),
                ('speculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_betail_var_items', to='PRODAGRIC.speculation')),
            ],
        ),
        migrations.CreateModel(
            name='MarchBetailIndItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_gen', models.FloatField(blank=True, null=True)),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('espece', models.CharField(max_length=255)),
                ('code_devise', models.CharField(max_length=255)),
                ('niveau1_id', models.IntegerField(blank=True, null=True)),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('valid_pfr', models.BooleanField(blank=True, null=True)),
                ('valid_pfp', models.BooleanField(blank=True, null=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_betail_ind_items', to='DIVADMIN.divisionadministrative')),
                ('indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_betail_ind_items', to='INDICATEUR.indicateur')),
                ('speculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_betail_ind_items', to='PRODAGRIC.speculation')),
            ],
        ),
        migrations.CreateModel(
            name='MarchAgricVarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('variable', models.IntegerField(blank=True, null=True)),
                ('nom_marche', models.CharField(max_length=255)),
                ('type_prix', models.CharField(max_length=255)),
                ('code_unite', models.CharField(max_length=255)),
                ('code_devise', models.CharField(max_length=255)),
                ('niveau1_id', models.IntegerField(blank=True, null=True)),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_agric_var_items', to='DIVADMIN.divisionadministrative')),
                ('speculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_agric_var_items', to='PRODAGRIC.speculation')),
            ],
        ),
        migrations.CreateModel(
            name='MarchAgricIndItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_gen', models.FloatField(blank=True, null=True)),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('code_devise', models.CharField(max_length=255)),
                ('niveau1_id', models.IntegerField(blank=True, null=True)),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('valid_pfr', models.BooleanField(blank=True, null=True)),
                ('valid_pfp', models.BooleanField(blank=True, null=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_agric_ind_items', to='DIVADMIN.divisionadministrative')),
                ('indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_agric_ind_items', to='INDICATEUR.indicateur')),
                ('speculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marche_agric_ind_items', to='PRODAGRIC.speculation')),
            ],
        ),
        migrations.CreateModel(
            name='ComextVarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('devise', models.TextField(blank=True, null=True)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('debut_campagne', models.IntegerField(blank=True, null=True)),
                ('fin_campagne', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('destination', models.TextField(blank=True, null=True)),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comext_var_items', to='DIVADMIN.divisionadministrative')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comext_var_items', to='MARCHE.produitcomext')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comext_var_items', to='INDICATEUR.variable')),
            ],
        ),
        migrations.CreateModel(
            name='ComextIndItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_gen', models.FloatField(blank=True, null=True)),
                ('unite_devise', models.TextField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('valid_pfr', models.BooleanField(blank=True, null=True)),
                ('valid_pfp', models.BooleanField(blank=True, null=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comext_ind_items', to='DIVADMIN.divisionadministrative')),
                ('indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comext_ind_items', to='INDICATEUR.indicateur')),
            ],
        ),
    ]
