# Generated by Django 3.2.5 on 2025-03-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DIVADMIN', '0001_initial'),
        ('PRODAGRIC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdVarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prod', models.FloatField(blank=True, null=True)),
                ('unite', models.TextField(blank=True, null=True)),
                ('categorie_spe', models.FloatField(blank=True, null=True)),
                ('debut_campagne', models.IntegerField(blank=True, null=True)),
                ('fin_campagne', models.IntegerField(blank=True, null=True)),
                ('valid_pfr', models.BooleanField(blank=True, null=True)),
                ('valid_pfp', models.BooleanField(blank=True, null=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodindust_items', to='DIVADMIN.divisionadministrative')),
                ('speculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodindust_items', to='PRODAGRIC.speculation')),
            ],
        ),
    ]
