# Generated by Django 3.2.5 on 2024-10-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('INDICATEUR', '0001_initial'),
        ('DIVADMIN', '0001_initial'),
        ('PARAMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieSpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCategorie', models.CharField(max_length=255)),
                ('nomCategorie', models.TextField(blank=True)),
                ('nomCategorie_ang', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productionagricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_production_agricole', models.FloatField()),
                ('rendement_production_agricole', models.FloatField()),
                ('quantite_production_agricole', models.FloatField()),
                ('source_production_agricole', models.CharField(max_length=255)),
                ('campagne_production_agricole', models.CharField(max_length=255)),
                ('annee_production_agricole', models.CharField(max_length=255)),
                ('pays_production_agricole', models.CharField(max_length=255)),
                ('methode_production_agricole', models.CharField(max_length=255)),
                ('statut_production_agricole', models.IntegerField()),
                ('produit_id', models.PositiveBigIntegerField()),
                ('bilan_id', models.PositiveBigIntegerField()),
                ('divisionadministrative_id', models.PositiveBigIntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSpeculation', models.CharField(max_length=255)),
                ('nomSpeculation', models.TextField(blank=True)),
                ('nomSpeculation_ang', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('categoriespe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speculations', to='PRODAGRIC.categoriespe')),
            ],
        ),
        migrations.CreateModel(
            name='ProdagricVarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricvar_items', to='PARAMS.campagne')),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricvar_items', to='DIVADMIN.divisionadministrative')),
                ('speculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricvar_items', to='PRODAGRIC.speculation')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricvar_items', to='INDICATEUR.variable')),
            ],
        ),
        migrations.CreateModel(
            name='ProdagricIndItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_gen', models.FloatField()),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('valid_pfr', models.BooleanField(blank=True, null=True)),
                ('valid_pfp', models.BooleanField(blank=True, null=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricind_items', to='PARAMS.campagne')),
                ('divisionadministrative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricind_items', to='DIVADMIN.divisionadministrative')),
                ('indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricind_items', to='INDICATEUR.indicateur')),
                ('speculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodagricind_items', to='PRODAGRIC.speculation')),
            ],
        ),
    ]
